
name: Webapp Checks (Disabled)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: No configured web apps
        run: echo "No web apps configured in .jig.yml"

